FROM tool

RUN apt-get update && \
    apt-get install libnuma-dev ca-certificates bsdmainutils bc curl -y

WORKDIR /etc/nebula
ADD ./ca.crt /etc/nebula/
ADD ./ca.key /etc/nebula/

WORKDIR /home/app
ADD ./run-nebula.sh /home/app/

WORKDIR /home/app
ADD ./client.yaml /home/app/

# ENTRYPOINT [ "/bin/bash", "-c", "/home/app/run-client.sh" ]
