name:                tool
version:             0.1.0.0
github:              "githubuser/tool"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tool#readme>

dependencies:
- base >= 4.7 && < 5
- dhall == 1.40.2
- template-haskell == 2.17.0.0
- prettyprinter == 1.7.1
- dhall-yaml == 1.2.10
- bytestring == 0.10.12.1
- process == 1.6.13.2
- text == 1.2.5.0
- directory == 1.3.6.2
- monad-parallel == 0.7.2.5
- dhall-json == 1.7.9
- optparse-applicative == 0.16.1.0
- Unique == 0.4.7.9
- filepath == 1.4.2.1
- aeson == 2.0.3.0

library:
  source-dirs: src

executables:
  tool-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tool

tests:
  tool-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tool
